import { supabaseAdmin } from "@/lib/supabaseAdmin";

type Props = {
  params: Promise<{
    reportId: string;
  }>;
};

export default async function VerificationPage({
  params,
}: Props) {
  const { reportId } = await params;

  const { data: report, error } =
    await supabaseAdmin
      .from("weather_reports")
      .select(
        `
        report_id,
        created_at,
        address,
        date_of_loss,
        payment_status
        `
      )
      .eq("report_id", reportId)
      .single();

  if (error || !report) {
    return (
      <main className="min-h-screen bg-slate-100 px-6 py-16">
        <div className="mx-auto max-w-2xl rounded-xl border border-slate-200 bg-white p-8 shadow-sm">
          <p className="text-sm font-semibold uppercase tracking-wide text-slate-500">
            WeatherSnap Report Verification
          </p>

          <h1 className="mt-3 text-3xl font-bold text-slate-900">
            Report Not Found
          </h1>

          <p className="mt-4 text-slate-600">
            We could not verify a WeatherSnap report with
            Report ID:
          </p>

          <p className="mt-2 font-mono text-lg font-semibold text-slate-900">
            {reportId}
          </p>
        </div>
      </main>
    );
  }

  const isVerified =
    report.payment_status === "paid";

  return (
    <main className="min-h-screen bg-slate-100 px-6 py-16">
      <div className="mx-auto max-w-2xl rounded-xl border border-slate-200 bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          WeatherSnap Report Verification
        </p>

        <div className="mt-4 flex items-center gap-3">
          <div
            className={`h-3 w-3 rounded-full ${
              isVerified
                ? "bg-emerald-500"
                : "bg-amber-500"
            }`}
          />

          <h1 className="text-3xl font-bold text-slate-900">
            {isVerified
              ? "Verified WeatherSnap Report"
              : "Report Exists"}
          </h1>
        </div>

        <p className="mt-4 text-slate-600">
          This page confirms that the Report ID below
          exists in the WeatherSnap system.
        </p>

        <div className="mt-8 divide-y divide-slate-200 rounded-lg border border-slate-200">
          <div className="p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Report ID
            </p>

            <p className="mt-1 font-mono text-lg font-semibold text-slate-900">
              {report.report_id}
            </p>
          </div>

          <div className="p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Property
            </p>

            <p className="mt-1 text-slate-900">
              {report.address}
            </p>
          </div>

          <div className="p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Date of Loss
            </p>

            <p className="mt-1 text-slate-900">
              {report.date_of_loss}
            </p>
          </div>

          <div className="p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Report Created
            </p>

            <p className="mt-1 text-slate-900">
              {new Date(
                report.created_at
              ).toLocaleString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "numeric",
                minute: "2-digit",
              })}
            </p>
          </div>

          <div className="p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Status
            </p>

            <p
              className={`mt-1 font-semibold ${
                isVerified
                  ? "text-emerald-700"
                  : "text-amber-700"
              }`}
            >
              {isVerified
                ? "Verified"
                : "Not Yet Verified"}
            </p>
          </div>
        </div>

        <p className="mt-8 text-sm leading-6 text-slate-500">
          Verification confirms that this Report ID was
          generated by WeatherSnap and matches the
          property and Date of Loss shown above.
        </p>
      </div>
    </main>
  );
}